// Generated by running 'go run cmd/parser/fiat.go'
package fiat

var (
	USD = newCurrency("USD") // USD is worth: $1.00000000 USD
	AUD = newCurrency("AUD") // AUD is worth: $0.65948879 USD
	BRL = newCurrency("BRL") // BRL is worth: $0.18448142 USD
	CAD = newCurrency("CAD") // CAD is worth: $0.72416278 USD
	CHF = newCurrency("CHF") // CHF is worth: $1.26128058 USD
	CLP = newCurrency("CLP") // CLP is worth: $0.00103033 USD
	CNY = newCurrency("CNY") // CNY is worth: $0.14025442 USD
	CZK = newCurrency("CZK") // CZK is worth: $0.04833066 USD
	DKK = newCurrency("DKK") // DKK is worth: $0.15755832 USD
	EUR = newCurrency("EUR") // EUR is worth: $1.17647751 USD
	GBP = newCurrency("GBP") // GBP is worth: $1.35528902 USD
	HKD = newCurrency("HKD") // HKD is worth: $0.12831806 USD
	HUF = newCurrency("HUF") // HUF is worth: $0.00299217 USD
	IDR = newCurrency("IDR") // IDR is worth: $0.00006063 USD
	ILS = newCurrency("ILS") // ILS is worth: $0.30091478 USD
	INR = newCurrency("INR") // INR is worth: $0.01136609 USD
	JPY = newCurrency("JPY") // JPY is worth: $0.00678547 USD
	KRW = newCurrency("KRW") // KRW is worth: $0.00072148 USD
	MXN = newCurrency("MXN") // MXN is worth: $0.05358257 USD
	MYR = newCurrency("MYR") // MYR is worth: $0.23701737 USD
	NOK = newCurrency("NOK") // NOK is worth: $0.10019179 USD
	NZD = newCurrency("NZD") // NZD is worth: $0.59426322 USD
	PHP = newCurrency("PHP") // PHP is worth: $0.01763948 USD
	PKR = newCurrency("PKR") // PKR is worth: $0.00353530 USD
	PLN = newCurrency("PLN") // PLN is worth: $0.27696312 USD
	RUB = newCurrency("RUB") // RUB is worth: $0.01212529 USD
	SEK = newCurrency("SEK") // SEK is worth: $0.10688601 USD
	SGD = newCurrency("SGD") // SGD is worth: $0.77957756 USD
	THB = newCurrency("THB") // THB is worth: $0.03155520 USD
	TRY = newCurrency("TRY") // TRY is worth: $0.02423855 USD
	TWD = newCurrency("TWD") // TWD is worth: $0.03292398 USD
	ZAR = newCurrency("ZAR") // ZAR is worth: $0.05723414 USD
	VND = newCurrency("VND") // VND is worth: $0.00003786 USD
	MAD = newCurrency("MAD") // MAD is worth: $0.11080332 USD
	IRR = newCurrency("IRR") // IRR is worth: $0.00002378 USD
	ARS = newCurrency("ARS") // ARS is worth: $0.00070273 USD
	RON = newCurrency("RON") // RON is worth: $0.23194322 USD
	UAH = newCurrency("UAH") // UAH is worth: $0.02431527 USD
	NGN = newCurrency("NGN") // NGN is worth: $0.00066290 USD
	AED = newCurrency("AED") // AED is worth: $0.27229408 USD
	COP = newCurrency("COP") // COP is worth: $0.00025163 USD
	EGP = newCurrency("EGP") // EGP is worth: $0.02072535 USD
	SAR = newCurrency("SAR") // SAR is worth: $0.26652843 USD
	BDT = newCurrency("BDT") // BDT is worth: $0.00821975 USD
	GHS = newCurrency("GHS") // GHS is worth: $0.09523810 USD
	BGN = newCurrency("BGN") // BGN is worth: $0.60117831 USD
	VES = newCurrency("VES") // VES is worth: $0.00651310 USD
)

func All() []Currency {
	return []Currency{
		USD, AUD, BRL, CAD, CHF, CLP, CNY, CZK, DKK, EUR, GBP, HKD, HUF, IDR, ILS, INR, JPY, KRW, MXN, MYR, NOK, NZD, PHP, PKR, PLN, RUB, SEK, SGD, THB, TRY, TWD, ZAR, VND, MAD, IRR, ARS, RON, UAH, NGN, AED, COP, EGP, SAR, BDT, GHS, BGN, VES,
	}
}
